export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/register'
export const HOME_ROUTE = '/'
//export const BASKET_ROUTE = '/basket'
export const REALT_ROUTE = '/realt'
export const PROFILE_ROUTE = '/profile'
export const USER_ROUTE = '/user'